### ISSUE TITLE
separation rank

### ISSUE THREAD

**Issue by ErikJhones** [noamrazin/gnn_interactions#1]
Hello. Great work. Could you please tell me how you measure the separation rank (for graphs) via python code?

**Comment by noamrazin** [comment]
Hi,

To the best of our knowledge, there is no efficient way to exactly measure the separation rank for an arbitrary function. In the paper, we bound the separation rank of certain GNNs with respect to a partition through the _walk index_ of the partition --- the number of walks (of a certain length) originating from its boundary.

The walk indices relevant for the Walk Index Sparsification (WIS) algorithm are computed in [edges_removal/walk_index_sparsification.py](https://github.com/noamrazin/gnn_interactions/blob/master/edges_removal/walk_index_sparsification.py). For convenience, we added in [edges_removal/walk_index.py](https://github.com/noamrazin/gnn_interactions/blob/master/edges_removal/walk_index.py) a function for computing arbitrary walk indices.

We hope this answers your question,
Noam
